services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pi_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB:${POSTGRES_DB:-product_intel}
      - POSTGRES_USER:${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD:-app_password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-product_intel}"]
      interval: 5s
      timeout: 5s
      retries: 10

#  backend:
#    build: ./backend
#    container_name: pi_backend
#    restart: unless-stopped
#    env_file: .env
#    depends_on:
#      db:
#        condition: service_healthy
#      ports:
#        - "8000:8000"
#      volumes:
#        - media:/app/media
#        - ./documents:/app/documents

#  frontend:
#    build: ./backend
#    container_name: pi_backend
#    restart: unless-stopped
#    env_file: .env
#    depends_on:
#      db:
#        condition: service_healthy
#      ports:
#        - "8000:8000"
#      volumes:
#        - media:/app/media
#        - ./documents:/app/documents

volumes:
  pgdata:
  media: